apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resources.core.variant.run
spec:
  group: core.variant.run
  versions:
  - name: v1beta1
    served: true
    storage: true
  names:
    kind: Resource
    plural: resources
    singular: resource
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reconcilations.core.variant.run
spec:
  group: core.variant.run
  versions:
  - name: v1beta1
    served: true
    storage: true
  names:
    kind: Reconcilation
    plural: reconcilations
    singular: reconcilation
  scope: Namespaced
